cd TestHarness\bin\Debug
start TestHarness.exe
cd ..\..\..
cd Repository\bin\Debug
start Repository.exe
cd ..\..\..
cd Client\bin\Debug
start Client.exe
cd ..\..\..
cd Client2\bin\Debug
start Client2.exe
cd ..\..\..